server:
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: todo-app
  cloud:
    aws:
      region:
        static: eu-central-1
      sns:
        enabled: false

management:
  health:
    jms:
      enabled: false # don't verify the health of the JMS broker
  cloudwatch:
    metrics:
      export:
        enabled: true
        namespace: stratospheric
        step: 1m
  metrics:
    tags:
      environment: ${ENVIRONMENT_NAME}

# configuration of error-handling-spring-boot-starter (https://wimdeblauwe.github.io/error-handling-spring-boot-starter/)
error:
  handling:
    exception-logging: WITH_STACKTRACE

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database
  sharing-queue: stratospheric-todo-sharing
  external-url: https://app.stratospheric.dev
  auto-confirm-collaborations: false
  confirm-email-from-address: noreply@stratospheric.dev
  environment: ${ENVIRONMENT_NAME}
